"""Rig geometry -- GENERATED by make_rig.py. Do not hand-edit.

Corner coordinates are in OpenCV convention: +x right, +y DOWN, +z away from
the camera, origin at the plate centre. Physical +y (up) is negated here.
Units are millimetres.

    import cv2, numpy as np
    from rig_geometry import OBJ_POINTS, MARKER_IDS, DICT
    board = cv2.aruco.Board(
        np.array(OBJ_POINTS, dtype=np.float32),
        cv2.aruco.getPredefinedDictionary(DICT),
        np.array(MARKER_IDS, dtype=np.int32))

Solve over the whole board rather than per-marker: four markers spanning
126 x 90 mm are far more stable than any one of them, and the
90 mm vertical spread is what makes pitch observable at all.
"""

DICT = 0  # cv2.aruco.DICT_4X4_50
MARKER_MM = 30.0
MARKER_IDS = [0, 1, 2, 3]
OBJ_POINTS = [
    [
        [
            -78.0,
            -60.0,
            0.0
        ],
        [
            -48.0,
            -60.0,
            0.0
        ],
        [
            -48.0,
            -30.0,
            0.0
        ],
        [
            -78.0,
            -30.0,
            0.0
        ]
    ],
    [
        [
            48.0,
            -60.0,
            0.0
        ],
        [
            78.0,
            -60.0,
            0.0
        ],
        [
            78.0,
            -30.0,
            0.0
        ],
        [
            48.0,
            -30.0,
            0.0
        ]
    ],
    [
        [
            48.0,
            30.0,
            0.0
        ],
        [
            78.0,
            30.0,
            0.0
        ],
        [
            78.0,
            60.0,
            0.0
        ],
        [
            48.0,
            60.0,
            0.0
        ]
    ],
    [
        [
            -78.0,
            30.0,
            0.0
        ],
        [
            -48.0,
            30.0,
            0.0
        ],
        [
            -48.0,
            60.0,
            0.0
        ],
        [
            -78.0,
            60.0,
            0.0
        ]
    ]
]
